CREATE DATABASE IF NOT EXISTS fixtures;
CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'Franklin5';
GRANT SELECT,UPDATE,INSERT,DELETE,DROP,CREATE ON fixtures.* TO 'admin'@'%';
FLUSH PRIVILEGES;